name: learn-github-actions
on:
  push:
    tags: ['v*']
env:
  WORKFLOW_VAR: 'Workflow var is set!!!'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        var: [0, 1]
    env:
      JOB_VAR: 'Job var is set!!!'
      MATRIX_VAR: ${{ matrix.var }}
    steps:
      - uses: actions/checkout@v2
      - name: Run check script
        run: ./.github/scripts/check.sh
        shell: bash
        env:
          STEP_VAR: 'Step var is set!!!'
          SECRET_VAR: ${{ secrets.SECRET_VAR }}
      - uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: test-output.txt

          # Check pwd
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-artifact
      - run: cat test-output.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'test-output.txt'
          token: ${{ secrets.GITHUB_TOKEN }}

